@startuml

interface ICserélhető {
  -- C# syntax --
  +{abstract} void Csere(ref int a, ref int b)
}

class Rendez implements ICserélhető {
  -RendezésiStratégia rs
  +Rendez(RendezésiStratégia rs)
  +void Rendezés(int[] T) { rs.Rendezés(T, this); }
  +void Csere(ref int a, ref int b)
}

interface RendezésiStratégia {
  +{abstract} void Rendezés(int[] T, ICserélhető cserélő)
}

Rendez o-down-> RendezésiStratégia : -rs
RendezésiStratégia ..> ICserélhető : <<uses>>
BuborékosRendezés .up.|> RendezésiStratégia
HatékonyBubRend .up.|> RendezésiStratégia
@enduml